# Generated by Django 3.1.3 on 2021-04-04 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('schedules', '0001_initial'),
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='modules',
                                    to='schedules.schedules'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modules',
            name='module_code',
            field=models.SlugField(max_length=45),
        ),
        migrations.AlterUniqueTogether(
            name='modules',
            unique_together={('module_code', 'schedule')},
        ),
    ]
