# Generated by Django 3.1.3 on 2021-04-10 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_auto_20210404_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_of_classes', to='modules.modules'),
        ),
    ]
