# Generated by Django 3.1.3 on 2021-04-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('modules', '0004_auto_20210412_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='name',
            field=models.CharField(max_length=124),
        ),
    ]
