# Generated by Django 3.1.3 on 2021-04-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_auto_20210412_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='name',
            field=models.CharField(choices=[('Lectures', 'Lectures'), ('Laboratory classes', 'Laboratory classes'), ('Auditorium classes', 'Auditorium classes'), ('Project classes', 'Project classes'), ('Seminar classes', 'Seminar classes'), ('Practical classes', 'Practical classes'), ('Lektorat', 'Lektorat'), ('Zajęcia z wychowania fizycznego', 'Zajęcia z wychowania fizycznego')], default='Lectures', max_length=31),
        ),
    ]
