# Generated by Django 3.1.3 on 2021-04-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('modules', '0006_auto_20210412_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='name',
            field=models.CharField(choices=[('Lectures', 'Lectures'), ('Laboratory classes', 'Laboratory classes'),
                                            ('Auditorium classes', 'Auditorium classes'),
                                            ('Project classes', 'Project classes'),
                                            ('Seminar classes', 'Seminar classes'),
                                            ('Practical classes', 'Practical classes'), ('Lektorat', 'Lektorat'),
                                            ('Zajęcia z wychowania fizycznego', 'Zajęcia z wychowania fizycznego'),
                                            ('Prace kontrolne i przejściowe', 'Prace kontrolne i przejściowe'),
                                            ('Conversation seminar', 'Conversation seminar'),
                                            ('Workshops', 'Workshops')], default='Lectures', max_length=31),
        ),
        migrations.AlterField(
            model_name='modules',
            name='name',
            field=models.CharField(max_length=192),
        ),
    ]
