# Generated by Django 3.1.3 on 2021-04-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('modules', '0007_auto_20210418_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
