# Generated by Django 3.1.3 on 2021-04-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0008_auto_20210418_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='language',
            field=models.CharField(default='pl', max_length=2),
        ),
    ]
