# Generated by Django 3.1.3 on 2021-06-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0011_remove_modules_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='name',
            field=models.CharField(choices=[('Lectures', 'Lectures'), ('Laboratory classes', 'Laboratory classes'), ('Auditorium classes', 'Auditorium classes'), ('Project classes', 'Project classes'), ('Seminar classes', 'Seminar classes'), ('Practical classes', 'Practical classes'), ('Lektorat', 'Lektorat'), ('Zajęcia z wychowania fizycznego', 'Zajęcia z wychowania fizycznego'), ('Prace kontrolne i przejściowe', 'Prace kontrolne i przejściowe'), ('Conversation seminar', 'Conversation seminar'), ('Workshops', 'Workshops'), ('Others', 'Others'), ('E-learning', 'E-learning')], default='Lectures', max_length=31),
        ),
    ]
