# Generated by Django 3.1.3 on 2021-02-21 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Degrees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pensum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('value', models.PositiveIntegerField()),
                ('limit', models.PositiveIntegerField(default=0, null=True)),
                ('year_of_studies', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('year_condition', models.CharField(choices=[('greater than', 'greater than'), ('equal to', 'equal to'), ('less than', 'less than'), ('N/A', 'N/A')], default='N/A', max_length=12)),
                ('is_procedure_for_a_doctoral_degree_approved', models.CharField(choices=[('True', 'YES'), ('N/A', 'N/A'), ('False', 'NO')], default='N/A', max_length=5)),
                ('has_scholarship', models.CharField(choices=[('True', 'YES'), ('N/A', 'N/A'), ('False', 'NO')], default='N/A', max_length=5)),
                ('degrees', models.ManyToManyField(related_name='pensum', to='employees.Degrees')),
                ('positions', models.ManyToManyField(blank=True, related_name='pensum', to='employees.Positions')),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('abbreviation', models.SlugField(max_length=5, unique=True)),
                ('e_mail', models.EmailField(max_length=45, unique=True)),
                ('year_of_studies', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_procedure_for_a_doctoral_degree_approved', models.BooleanField(default=False)),
                ('has_scholarship', models.BooleanField(default=False)),
                ('degree', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='employees', to='employees.degrees')),
                ('position', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='employees', to='employees.positions')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='employees.employees')),
            ],
            options={
                'ordering': ['abbreviation'],
            },
        ),
    ]
