# Generated by Django 3.1.3 on 2021-04-05 15:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pensum',
        ),
    ]
