# Generated by Django 3.1.3 on 2021-04-05 16:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('employees', '0002_auto_20210405_1704'),
    ]

    operations = [
    ]
