# Generated by Django 3.1.3 on 2021-04-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employees_pensum_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='part_of_job_time',
            field=models.FloatField(default=1),
        ),
    ]
