# Generated by Django 3.1.3 on 2021-05-16 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employees_part_of_job_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='has_scholarship',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='is_procedure_for_a_doctoral_degree_approved',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='year_of_studies',
        ),
    ]
