# Generated by Django 3.1.3 on 2021-05-16 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_auto_20210516_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='supervisor',
        ),
    ]
