# Generated by Django 3.1.3 on 2021-02-21 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('modules', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('classes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True,
                                                 related_name='order', serialize=False, to='modules.classes')),
                ('students_number', models.PositiveIntegerField()),
                ('order_number', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_hours', models.PositiveIntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans',
                                               to='employees.employees')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans',
                                            to='orders.orders')),
            ],
            options={
                'unique_together': {('order', 'employee')},
            },
        ),
    ]
