# Generated by Django 3.1.3 on 2021-06-23 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pensum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_threshold', models.FloatField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pensums', to='employees.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PensumBasicThresholdFactors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('factor_type', models.CharField(choices=[('Addition', 'Addition'), ('Multiplication', 'Multiplication')], default='Addition', max_length=14)),
                ('value', models.FloatField(default=1)),
                ('pensum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic_threshold_factors', to='schedules.pensum')),
            ],
        ),
        migrations.CreateModel(
            name='PensumAdditionalHoursFactors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('bachelor thesis', 'opieka nad pracą dyplomową na studiach inżynierskich lub licencjackich'), ('multi bachelor thesis', 'opieka nad zespołową pracą dyplomową na studiach inżynierskich lub licencjackich'), ('master thesis', 'opieka nad pracą dyplomową na studiach magisterskich'), ('multi master thesis', 'opieka nad zespołową pracą dyplomową na studiach magisterskich'), ('doctoral student before opening procedure for PhD', 'opieka nad doktorantem przed otwarciem przewodu'), ('doctoral student after opening procedure for PhD', 'opieka nad doktorantem po otwarciu przewodu'), ('individual program student', 'opieka nad studentem studiującym w ramach indywidualnej organizacji studiów'), ('student research group', 'opieka nad kołem naukowym'), ('international program student', 'opieka nad studentem, stażystą lub stypendystą odbywającym kształcenie w ramach programów krajowych lub międzynarodowych'), ('custom additional hours', 'dodatkowa liczba godzin z innego tytułu')], default='bachelor thesis', max_length=64)),
                ('value_per_unit', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField(default=1)),
                ('description', models.CharField(blank=True, max_length=128)),
                ('pensum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_hours_factors', to='schedules.pensum')),
            ],
        ),
        migrations.AddField(
            model_name='pensum',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pensums', to='schedules.schedules'),
        ),
        migrations.CreateModel(
            name='PensumReductions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(choices=[('Rektor', 'Rektor'), ('Prorektor', 'Prorektor'), ('Dziekan Wydziału', 'Dziekan Wydziału'), ('Dyrektor Centrum Badawczego', 'Dyrektor Centrum Badawczego'), ('Dyrektor Szkoły Doktorskiej', 'Dyrektor Szkoły Doktorskiej'), ('Przewodniczący Rady Dyscypliny Naukowej', 'Przewodniczący Rady Dyscypliny Naukowej'), ('Dyrektor Bentrum Dydaktycznego', 'Dyrektor Bentrum Dydaktycznego'), ('Prodziekan', 'Prodziekan'), ('Zastępca Dyrektora Centrum Badawczego', 'Zastępca Dyrektora Centrum Badawczego'), ('Zastępca Dyrektora Szkoły Doktorskiej', 'Zastępca Dyrektora Szkoły Doktorskiej'), ('Zastępca Przewodniczącego Rady Dyscypliny Naukowej', 'Zastępca Przewodniczącego Rady Dyscypliny Naukowej'), ('Zastępca Dyrektora Centrum Dydaktycznego', 'Zastępca Dyrektora Centrum Dydaktycznego'), ('Dyrektor Instytutu', 'Dyrektor Instytutu'), ('Kierownik Katedry', 'Kierownik Katedry'), ('Pełnomocnik Rektora ds. Jakości Kształcenia', 'Pełnomocnik Rektora ds. Jakości Kształcenia'), ('Członek Uczelnianego Zespołu Audytu Dydaktycznego', 'Członek Uczelnianego Zespołu Audytu Dydaktycznego'), ('Pełnomocnik Dziekana ds. Jakości Kształcenia', 'Pełnomocnik Dziekana ds. Jakości Kształcenia')], max_length=50)),
                ('pensum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reduction', to='schedules.pensum')),
            ],
            options={
                'unique_together': {('pensum', 'function')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='pensum',
            unique_together={('schedule', 'employee')},
        ),
    ]
