# Generated by Django 3.1.3 on 2021-04-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('schedules', '0003_auto_20210405_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pensum',
            name='value',
        ),
        migrations.AlterField(
            model_name='pensumfactors',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
