# Generated by Django 3.1.3 on 2021-04-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('schedules', '0004_auto_20210405_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pensumfactors',
            name='addition_value',
        ),
        migrations.RemoveField(
            model_name='pensumfactors',
            name='multiplication_value',
        ),
        migrations.AddField(
            model_name='pensumfactors',
            name='factor_type',
            field=models.CharField(choices=[('Addition', 'Addition'), ('Multiplication', 'Multiplication')],
                                   default='Addition', max_length=14),
        ),
    ]
