# Generated by Django 3.1.3 on 2021-04-07 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_pensumfactors_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='PensumReductions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(choices=[('Rektor', 'Rektor'), ('Prorektor', 'Prorektor'), ('Dziekan Wydziału', 'Dziekan Wydziału'), ('Dyrektor Centrum Badawczego', 'Dyrektor Centrum Badawczego'), ('Dyrektor Szkoły Doktorskiej', 'Dyrektor Szkoły Doktorskiej'), ('Przewodniczący Rady Dyscypliny Naukowej', 'Przewodniczący Rady Dyscypliny Naukowej'), ('Dyrektor Bentrum Dydaktycznego', 'Dyrektor Bentrum Dydaktycznego'), ('Prodziekan', 'Prodziekan'), ('Zastępca Dyrektora Centrum Badawczego', 'Zastępca Dyrektora Centrum Badawczego'), ('Zastępca Dyrektora Szkoły Doktorskiej', 'Zastępca Dyrektora Szkoły Doktorskiej'), ('Zastępca Przewodniczącego Rady Dyscypliny Naukowej', 'Zastępca Przewodniczącego Rady Dyscypliny Naukowej'), ('Zastępca Dyrektora Centrum Dydaktycznego', 'Zastępca Dyrektora Centrum Dydaktycznego'), ('Dyrektor Instytutu', 'Dyrektor Instytutu'), ('Kierownik Katedry', 'Kierownik Katedry'), ('Pełnomocnik Rektora ds. Jakości Kształcenia', 'Pełnomocnik Rektora ds. Jakości Kształcenia'), ('Członek Uczelnianego Zespołu Audytu Dydaktycznego', 'Członek Uczelnianego Zespołu Audytu Dydaktycznego'), ('Pełnomocnik Dziekana ds. Jakości Kształcenia', 'Pełnomocnik Dziekana ds. Jakości Kształcenia')], max_length=50)),
                ('pensum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reductions', to='schedules.pensum')),
            ],
            options={
                'unique_together': {('pensum', 'function')},
            },
        ),
    ]
