# Generated by Django 3.1.3 on 2021-04-08 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0007_pensumreductions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensumreductions',
            name='pensum',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reductions', to='schedules.pensum'),
        ),
    ]
