# Generated by Django 3.1.3 on 2021-04-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0009_auto_20210408_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='pensum',
            name='part_of_job_time',
            field=models.FloatField(default=1),
        ),
    ]
