# Generated by Django 3.1.3 on 2021-04-23 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0010_pensum_part_of_job_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pensum',
            name='part_of_job_time',
        ),
    ]
