# Generated by Django 3.1.3 on 2021-04-24 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0011_remove_pensum_part_of_job_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PensumAdditionalHoursFactors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('bachelor thesis', 'opieka nad pracą dyplomową na studiach inżynierskich lub licencjackich'), ('multi bachelor thesis', 'opieka nad zespołową pracą dyplomową na studiach inżynierskich lub licencjackich'), ('master thesis', 'opieka nad pracą dyplomową na studiach magisterskich'), ('multi master thesis', 'opieka nad zespołową pracą dyplomową na studiach magisterskich'), ('doctoral student before opening procedure for PhD', 'opieka nad doktorantem przed otwarciem przewodu'), ('doctoral student after opening procedure for PhD', 'opieka nad doktorantem po otwarciu przewodu'), ('individual program student', 'opieka nad studentem studiującym w ramach indywidualnej organizacji studiów'), ('student research group', 'opieka nad kołem naukowym'), ('international program student', 'opieka nad studentem, stażystą lub stypendystą odbywającym kształcenie w ramach programów krajowych lub międzynarodowych')], default='bachelor thesis', max_length=64)),
                ('value_per_unit', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField(default=1)),
                ('description', models.CharField(blank=True, max_length=128)),
                ('pensum', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_hours_factors', to='schedules.pensum')),
            ],
        ),
    ]
