# Generated by Django 3.1.3 on 2021-04-24 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0012_pensumadditionalhoursfactors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensumadditionalhoursfactors',
            name='pensum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_hours_factors', to='schedules.pensum'),
        ),
    ]
