# Generated by Django 3.1.3 on 2021-04-24 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0013_auto_20210424_1855'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PensumFactors',
            new_name='PensumBasicThresholdFactors',
        ),
    ]
