# Generated by Django 3.1.3 on 2021-04-24 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0014_auto_20210424_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensumbasicthresholdfactors',
            name='pensum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic_threshold_factors', to='schedules.pensum'),
        ),
    ]
