# Generated by Django 3.1.3 on 2021-04-25 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0009_modules_language'),
        ('schedules', '0016_auto_20210425_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamsAdditionalHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Written', 'Written'), ('Oral', 'Oral')], default='Written', max_length=8)),
                ('portion', models.FloatField(default=1)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams_additional_horus', to='modules.modules')),
                ('pensum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams_additional_horus', to='schedules.pensum')),
            ],
            options={
                'unique_together': {('pensum', 'module')},
            },
        ),
    ]
