# Generated by Django 3.1.3 on 2021-04-25 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0009_modules_language'),
        ('schedules', '0017_examsadditionalhours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsadditionalhours',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams_additional_hours', to='modules.modules'),
        ),
        migrations.AlterField(
            model_name='examsadditionalhours',
            name='pensum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams_additional_hours', to='schedules.pensum'),
        ),
    ]
